// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.Api.Data;

#nullable disable

namespace TravelPlanner.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612025420_HospedagemOpcionalReserva")]
    partial class HospedagemOpcionalReserva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.Api.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<int>("RoteiroDiarioId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RoteiroDiarioId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("PontoTuristicoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PontoTuristicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.CategoriaDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasDespesa");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("ChecklistItens");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.ContaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoedaPadrao")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ViajanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViajanteId")
                        .IsUnique();

                    b.ToTable("ContasFinanceiras");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaDespesaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaDespesaId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Guia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Guias");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Hospedagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.ToTable("Hospedagens");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("GuiaId")
                        .HasColumnType("int");

                    b.Property<int?>("HospedagemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("GuiaId");

                    b.HasIndex("HospedagemId");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.PacoteDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("int");

                    b.Property<int>("PacoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacoteId");

                    b.ToTable("PacoteDias");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.PontoTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OpenTripMapId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.ToTable("PontosTuristicos");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GuiaId")
                        .HasColumnType("int");

                    b.Property<int?>("HospedagemId")
                        .HasColumnType("int");

                    b.Property<int?>("PacoteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaxaPlataforma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidoGuia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.HasIndex("HospedagemId");

                    b.HasIndex("PacoteId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.RoteiroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("RoteirosDiarios");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Transporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Companhia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViajanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("ViajanteId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viajante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PreferenciasViagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Viajantes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Administrador", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Usuario", "Usuario")
                        .WithOne("Administrador")
                        .HasForeignKey("TravelPlanner.Api.Models.Administrador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Atividade", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.RoteiroDiario", "RoteiroDiario")
                        .WithMany("Atividades")
                        .HasForeignKey("RoteiroDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoteiroDiario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Avaliacao", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.PontoTuristico", "PontoTuristico")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("PontoTuristicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlanner.Api.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PontoTuristico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.ChecklistItem", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("ChecklistItens")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.ContaFinanceira", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Viajante", "Viajante")
                        .WithOne("ContaFinanceira")
                        .HasForeignKey("TravelPlanner.Api.Models.ContaFinanceira", "ViajanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Viajante");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Despesa", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("CategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlanner.Api.Models.Reserva", "Reserva")
                        .WithMany("Despesas")
                        .HasForeignKey("ReservaId");

                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("Despesas")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaDespesa");

                    b.Navigation("Reserva");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Documento", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("Documentos")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Guia", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Usuario", "Usuario")
                        .WithOne("Guia")
                        .HasForeignKey("TravelPlanner.Api.Models.Guia", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Hospedagem", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Destino", "Destino")
                        .WithMany("Hospedagens")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Notificacao", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Pacote", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlanner.Api.Models.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelPlanner.Api.Models.Hospedagem", "Hospedagem")
                        .WithMany()
                        .HasForeignKey("HospedagemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destino");

                    b.Navigation("Guia");

                    b.Navigation("Hospedagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.PacoteDia", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Pacote", "Pacote")
                        .WithMany("Dias")
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.PontoTuristico", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Destino", "Destino")
                        .WithMany("PontosTuristicos")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Reserva", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelPlanner.Api.Models.Hospedagem", "Hospedagem")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedagemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.Api.Models.Pacote", "Pacote")
                        .WithMany()
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("Reservas")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guia");

                    b.Navigation("Hospedagem");

                    b.Navigation("Pacote");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.RoteiroDiario", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("RoteirosDiarios")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Transporte", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Viagem", "Viagem")
                        .WithMany("Transportes")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Usuario", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viagem", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Destino", "Destino")
                        .WithMany("Viagens")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlanner.Api.Models.Viajante", "Viajante")
                        .WithMany("Viagens")
                        .HasForeignKey("ViajanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Viajante");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viajante", b =>
                {
                    b.HasOne("TravelPlanner.Api.Models.Usuario", "Usuario")
                        .WithOne("Viajante")
                        .HasForeignKey("TravelPlanner.Api.Models.Viajante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.CategoriaDespesa", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Destino", b =>
                {
                    b.Navigation("Hospedagens");

                    b.Navigation("PontosTuristicos");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Hospedagem", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Pacote", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.PontoTuristico", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Reserva", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.RoteiroDiario", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Guia");

                    b.Navigation("Notificacoes");

                    b.Navigation("Viajante");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viagem", b =>
                {
                    b.Navigation("ChecklistItens");

                    b.Navigation("Despesas");

                    b.Navigation("Documentos");

                    b.Navigation("Reservas");

                    b.Navigation("RoteirosDiarios");

                    b.Navigation("Transportes");
                });

            modelBuilder.Entity("TravelPlanner.Api.Models.Viajante", b =>
                {
                    b.Navigation("ContaFinanceira");

                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
